@startuml
left to right direction
package UserAggregation {
    object User {
        ユーザーID
        ユーザー名
        年
        性別
        プレミアム会員
        プロフィール画像
        自己紹介
        居住地
        出身地
        有効/無効
    }
}

package LikeAggregation {
    object Like {
        いいねID
        いいねしたユーザーID
        いいねされたユーザーID
        マッチング状態
    }
}

package MessageAggregation {
    object Message {
        メッセージID
        いいねしたユーザーID
        いいねされたユーザーID
        既読/未読
    }
}

package BlockAggregation {
    object Block{
        ブロックID
        ブロックしたユーザーID
        ブロックされたユーザーID
    }
}

User --> Like:Refer to ユーザーID
User --> Message:Refer to ユーザーID
User --> Block:Refer to ユーザーID

note right of Like
マッチング状態は最初はかならず非マッチング
同じ相手には1回しかいいねはできない
ブロックされている相手にはできない
end note

note right of Message
マッチングした相手にしか送れない
ブロックされている相手には送れない
end note

note right of Block
ブロックは同じ相手には1回しかできない
end note

@enduml