@startuml
left to right direction
actor "User" as User
rectangle TargetUser{
    usecase "いいねする" as Like
    usecase "メッセージを送る" as SendMessage
    usecase "ブロックする" as Block
}
User --> Like
User --> SendMessage
User --> Block
@enduml