@startuml
actor "User" as User
left to right direction
rectangle TargetUser{
    usecase "いいねする" as Like
    usecase "メッセージを送る" as SendMessage
    usecase "ブロックする" as Block
    usecase "ユーザーを検索する\n(Query)" as SearchUser
}

rectangle TargetLike{
    usecase "いいねを返す" as Matching
    usecase "いいねを却下する" as UnMatching
}
User --> Like
User --> SendMessage
User --> Block
User --> SearchUser

User --> Matching
User --> UnMatching

@enduml